### ISSUE TITLE
Problem in installing bahmni on ubuntu 14.04

### ISSUE THREAD

**Issue by ahmedkhak** [Bhamni/bahmni-docker#7]
I am trying to install bahmni on my ubuntu 14.04 server. I am following steps which are mentioned in https://bahmni.atlassian.net/wiki/display/BAH/Bahmni+Using+Docker for linux. Now I didn't write that line in hosts file "192.168.59.103  dockerhost ", and i am trying to access bahmni using "localhost". Now i can access "openmrs", "openelis" and "OpenERP" using localhost but i am unable to access "https://localhost/bahmni/home". When i try to access that url "it works" tomcat page appears.

Please guide me how to solve that. Thank You

**Comment by sravanthi17** [comment]
you should use your docker's IP instead of localhost.

Example: if your docker ip is 192.168.59.103 
https://192.168.59.103/bahmni/home 

run  "boot2docker ip" to know your docker ip

**Comment by aj-jaswanth** [comment]
Which profile (BAHMNI_PROFILE) are you using?

**Comment by ahmedkhak** [comment]
We are "common" profile, but problem is we are on live server, so how can we access it from other machine ?

**Comment by aj-jaswanth** [comment]
It can't be "common" profile. It can be any of the profiles specified under "Installing Bahmni" section in https://bahmni.atlassian.net/wiki/display/BAH/Bahmni+Using+Docker. Are you using it only for production or for any development?

**Comment by ahmedkhak** [comment]
It's "prod" yes, I am installing on a ubuntu instance which has an ip. How would I access the installations from the ip?

**Comment by aj-jaswanth** [comment]
1. Are you able to access tomcat on 8080 port?
2. Run 'docker ps' and send the output.
3. Check if apache container is running on 80 port. And also check if 80 port is opened by firewall.

**Comment by ahmedkhak** [comment]
okay, i am on ubuntu live server and 

when i execute "./bahmni start", that output is shown
`
BAHMNI_PROFILE not set, using 'mrs' as default option.  The possible values are all, mrs, mrs-elis, mrs-erp, mrs-demo, prod
Starting the containers
Starting profiles_mysql_1...
Starting profiles_web_1...
Cannot start container 0eccaf78431990c292736b6f684bf8833b53061fd1d492002e152dba5a13d551: Cannot link to a non running container: /profiles_pgsql_1 AS /profiles_web_1/profiles_pgsql_1
`

and when i execute "docker ps", that output is shown
`
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                              NAMES
f788a2811dea        bahmni/mysql        "/entrypoint.sh mysql"   5 days ago          Up 5 minutes        0.0.0.0:3302->3302/tcp, 3306/tcp   profiles_mysql_1
`

i also execute that command 
`sudo ufw disable`

and after that i reboot the server. Please guide me how to access mysql and other things from other machine.

**Comment by aj-jaswanth** [comment]
You said in your first comment that the browser is displaying 'It Works!' page of tomcat when accessing bahmni, it might be because of another tomcat server running on 80 port. Stop it.
According to the above comment. Only MySQL container is running. Others are down.
You haven't set any profile. So, it was picking up mrs profile by default. But, it is not desired in production.
Try running the following commands in the bahmni-docker directory:
Do 'git pull' inside bahmni-docker directory.
1. export BAHMNI_PROFILE='prod'.
Try adding this line to your shell's rc file. For example, as you are using Ubuntu, it most probably uses the bash shell. Add the line at the end of the .bashrc file in your home directory.
2. ./bahmni stop
3. ./bahmni update
4. If you don't have any important data to retain in your server, run ./bahmni clean and ./bahmni install
5. ./bahmni start

**Comment by jmgihana** [comment]
Hi ahmedkak, 

I once had a similar issue like yours. The MySQL container couldn't communicate to profiles_web and profiles_apache. What I did was to replace the IPs in the MySQL docker container's host file with the host IP. Preferably I would edit all the host files of the containers and put in the host IP, then run the docker commit command.

First do what aj-jaswanth suggested and if the issue persists, try my suggestion.

Thanks

**Comment by ahmedkhak** [comment]
Dear @aj-jaswanth 

I followed your steps and added "export BAHMNI_PROFILE='prod'" in .bashrc file. Aftet that i did "./bahmni stop" and then "./bahmni update" and  then "./bahmni clean" and then "./bahmni install" and then "./bahmni start". But on "./bahmni start" output was like 

`BAHMNI_PROFILE not set, using 'mrs' as default option.  The possible values are all, mrs, mrs-elis, mrs-erp, mrs-demo, prod
Starting the containers`

and after that "docker ps" reponse was like

`CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                                                                NAMES
d9b25555586c        bahmni/apache       "httpd-foreground"       9 minutes ago       Up 9 minutes        0.0.0.0:443->443/tcp                                                 profiles_apache_1
fe6143108cf6        bahmni/web          "/root/.OpenMRS/setup"   9 minutes ago       Up 9 minutes        8000/tcp, 0.0.0.0:8020->8020/tcp, 8030/tcp, 0.0.0.0:8080->8080/tcp   profiles_web_1
a7f09a9ace0c        bahmni/mysql        "/entrypoint.sh mysql"   9 minutes ago       Up 9 minutes        0.0.0.0:3302->3302/tcp, 3306/tcp                                     profiles_mysql_1
`

**Comment by aj-jaswanth** [comment]
Please run source ~/.bashrc and run those commands again.

**Comment by ahmedkhak** [comment]
i did the same, when i execute "./bahmni stop" i get that output

`Stopping the containers
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.main", line 39, in main
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.docopt_command", line 21, in sys_dispatch
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.command", line 27, in dispatch
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.docopt_command", line 24, in dispatch
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.command", line 57, in perform_command
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.command", line 78, in get_project
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.config", line 142, in load
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.config", line 166, in make_service_dict
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.config", line 192, in resolve_extends
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.config", line 558, in load_yaml
  File "/code/build/docker-compose/out00-PYZ.pyz/yaml", line 93, in safe_load
  File "/code/build/docker-compose/out00-PYZ.pyz/yaml", line 71, in load
  File "/code/build/docker-compose/out00-PYZ.pyz/yaml.constructor", line 37, in get_single_data
  File "/code/build/docker-compose/out00-PYZ.pyz/yaml.composer", line 36, in get_single_node
  File "/code/build/docker-compose/out00-PYZ.pyz/yaml.composer", line 55, in compose_document
  File "/code/build/docker-compose/out00-PYZ.pyz/yaml.composer", line 84, in compose_node
  File "/code/build/docker-compose/out00-PYZ.pyz/yaml.composer", line 133, in compose_mapping_node
  File "/code/build/docker-compose/out00-PYZ.pyz/yaml.composer", line 64, in compose_node
  File "/code/build/docker-compose/out00-PYZ.pyz/yaml.parser", line 98, in check_event
  File "/code/build/docker-compose/out00-PYZ.pyz/yaml.parser", line 449, in parse_block_mapping_value
  File "/code/build/docker-compose/out00-PYZ.pyz/yaml.scanner", line 115, in check_token
  File "/code/build/docker-compose/out00-PYZ.pyz/yaml.scanner", line 149, in need_more_tokens
  File "/code/build/docker-compose/out00-PYZ.pyz/yaml.scanner", line 289, in stale_possible_simple_keys
yaml.scanner.ScannerError: while scanning a simple key
  in "/root/bahmni/bahmni-docker/common.yml", line 2, column 1
could not found expected ':'
  in "/root/bahmni/bahmni-docker/common.yml", line 3, column 1
`

that is shown on "./bahmni clean" and "./bahmni start", but it is not showing that message on "./bahmni update"

**Comment by ahmedkhak** [comment]
I checked it using that url "m.y.i.p:8080/openmrs", it is showing openmrs login page, but "m.y.i.p:8080/openelis" is not working and "m.y.i.p:8069", but for "openelis" that page is shown 

`Apache Tomcat/7.0.52 (Ubuntu)`

**Comment by ahmedkhak** [comment]
Thank You @aj-jaswanth

Now "openmrs", "openelis" and "openerp" are running, and i am able to sign in. But still i am not able to access "m.y.i.p/bahmni/home", it is showing "404 not found". Our "common.yml" is like 

apache:
 image: bahmni/apache
 hostname: apache
 ports:
- "443:443"
  web:
  image: bahmni/web
  hostname: web
  ports:
- "8080:8080"
- "8020:8020"
  
  environment:
- OPENMRS_RUNTIME_PROPERTIES_FILE=/root/.OpenMRS/openmrs-runtime.properties
- MYSQL=profiles_mysql_1
- PGSQL=profiles_pgsql_1
- OPENERP=profiles_openerp_1
  expose:
- "8080"
- "8030"

mysql:
 image: bahmni/mysql
 hostname: mysql
 environment: 
- STARTUP_SQL=/tmp/mysql_backup.sql
  ports:
- "3302:3302"

pgsql:
 image: bahmni/pgsql
 hostname: pgsql
 ports:
- "5433:5433"  

openerp:
 image: bahmni/erp
 hostname: openerp
 ports:
- "8069:8069"
  environment:
- DB_HOST=pgsql

openerp:
 image: bahmni/erp
 hostname: openerp
 ports:
- "8069:8069"
  environment:
- DB_HOST=pgsql
  `

**Comment by ahmedkhak** [comment]
@jmbabazi how can i access "MySQL docker container's host file" ?

**Comment by aj-jaswanth** [comment]
It seems that you have changed port numbers for mysql and postgres in common.yml. Do you have other services running on the same port?

**Comment by jmgihana** [comment]
I think if you able to access openmrs. That mean both bahmni/web and bahmni/mysql container are working fine. Can you check if bahmni/apache is listed in the outputs of this command "docker ps" if bahmni/apache is listed . Try running "https://yourIP/home" . NOTE that its "https" not http and its "/home" not /bahmni/home.

Tell me how it goes.

Thanks!

**Comment by ahmedkhak** [comment]
@jmbabazi thank you. I was trying url using "http", but it is working with "https".

Thank You for your help

**Comment by ahmedkhak** [comment]
is it possible that i access "/bahmni/web" without https ? I am asking that because it takes too much time to load login form and it takes too much to load other pages

**Comment by aj-jaswanth** [comment]
No. Only HTTPS is allowed. But, that might not be the reason of slow page loading. How much time is it taking on an average to load pages? What is the speed of your network connection? Which browser are you using?

**Comment by jmgihana** [comment]
Why do you want to access /bahmni/web without https? I believe if you disable ssl and change ports in the bahmni/apache container you can be able access via http but I am wondering why you would want that.

**Comment by ahmedkhak** [comment]
Actually we don't have https enabled on our server, maybe that is why response is always late or sometimes in bahmni ajax calls we get java errors. @jmbabazi you mean we need to change ports in "common.yml" files, please guide me for that.

**Comment by ahmedkhak** [comment]
Document Upload page is not working, in browser console i am getting these errors which are like 

![Image of Yaktocat](http://s29.postimg.org/e9gnqkcpz/github_forums.png)
